import "./globals.css";
import type { Metadata } from "next";
import HeaderMenu from "./_components/Menu/HeaderMenu";
import "./_customCSS/textEffect.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="font-helvetica mt-20 bg-customWhite text-darkTurquoise">
				<HeaderMenu />
				{children}
			</body>
		</html>
	);
}
